"""
DHCP Configuration Generator Service

Generates ISC DHCP server configuration files (dhcpd.conf) from database
"""
from sqlalchemy.orm import Session
from datetime import datetime
from ipaddress import IPv4Network
from typing import Optional
import json
import os
from ..models.ip_range import IPRange
from ..models.device import Device
from ..models.dhcp_config import DHCPConfig
from ..config import settings


def generate_dhcpd_conf(db: Session) -> str:
    """
    Generate ISC DHCP dhcpd.conf configuration file content

    Args:
        db: Database session

    Returns:
        Complete dhcpd.conf file content as string
    """
    output = []

    # Header with metadata
    output.append("# DHCP Configuration File")
    output.append("# Generated by DHCP Admin Panel")
    output.append(f"# Generated at: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC")
    output.append("#")
    output.append("# WARNING: This file is auto-generated. Manual changes will be overwritten.")
    output.append("#")
    output.append("")

    # Global DHCP options
    output.append("# Global DHCP Options")
    output.append("default-lease-time 600;")
    output.append("max-lease-time 7200;")
    output.append("authoritative;")
    output.append("")
    output.append("# Allow booting")
    output.append("allow booting;")
    output.append("allow bootp;")
    output.append("")

    # Get all active IP ranges (including Docker bridge network from database)
    ip_ranges = db.query(IPRange).filter(IPRange.is_active == True).order_by(IPRange.name).all()

    if not ip_ranges:
        output.append("# No active IP ranges configured")
        output.append("")

    # ========== PART 1: Subnet Declarations (without hosts) ==========
    output.append("# ========================================")
    output.append("# SUBNET DECLARATIONS")
    output.append("# ========================================")
    output.append("")

    for ip_range in ip_ranges:
        output.append(f"# Subnet: {ip_range.name}")
        if ip_range.description:
            output.append(f"# Description: {ip_range.description}")

        # Calculate network information
        network = IPv4Network(f"{ip_range.network_address}/{ip_range.cidr}", strict=False)
        netmask = str(network.netmask)

        # Subnet declaration
        output.append(f"subnet {ip_range.network_address} netmask {netmask} {{")

        # Subnet options
        if ip_range.gateway:
            output.append(f"    option routers {ip_range.gateway};")

        if ip_range.dns_servers:
            try:
                dns_list = json.loads(ip_range.dns_servers)
                if dns_list:
                    dns_string = ', '.join(dns_list)
                    output.append(f"    option domain-name-servers {dns_string};")
            except json.JSONDecodeError:
                pass  # Skip invalid JSON

        if ip_range.domain_name:
            output.append(f"    option domain-name \"{ip_range.domain_name}\";")

        output.append("")

        # DHCP Pool for dynamic IP allocation
        if ip_range.pool_start and ip_range.pool_end:
            output.append("    # Dynamic IP allocation pool")
            output.append(f"    range {ip_range.pool_start} {ip_range.pool_end};")
        else:
            output.append("    # No dynamic pool configured for this subnet")

        output.append("}")
        output.append("")

    # ========== PART 2: Global Host Declarations ==========
    output.append("# ========================================")
    output.append("# STATIC HOST RESERVATIONS (Global)")
    output.append("# ========================================")
    output.append("# Host declarations are global and not")
    output.append("# limited to the subnet they're declared in")
    output.append("")

    # Get all active devices across all ranges
    all_devices = db.query(Device)\
        .filter(Device.is_active == True)\
        .order_by(Device.hostname)\
        .all()

    if all_devices:
        for device in all_devices:
            # Get the IP range for context comment
            ip_range = db.query(IPRange).filter(IPRange.id == device.ip_range_id).first()
            range_name = ip_range.name if ip_range else "Unknown Range"

            output.append(f"# {device.hostname} - {range_name}")
            if device.description:
                output.append(f"# {device.description}")

            output.append(f"host {device.hostname} {{")
            output.append(f"    hardware ethernet {device.mac_address};")
            output.append(f"    fixed-address {device.ip_address};")
            output.append("}")
            output.append("")
    else:
        output.append("# No static host reservations configured")
        output.append("")

    # Footer
    output.append("# End of DHCP configuration")
    output.append("")

    return '\n'.join(output)


def save_dhcp_config_to_file(content: str, file_path: str = None) -> str:
    """
    Save DHCP configuration content to file

    Args:
        content: Configuration file content
        file_path: Path to save file (default from settings)

    Returns:
        Path where file was saved

    Raises:
        IOError: If file cannot be written
    """
    if file_path is None:
        file_path = settings.DHCP_CONFIG_PATH

    # Create directory if it doesn't exist
    os.makedirs(os.path.dirname(file_path), exist_ok=True)

    # Write to temporary file first (atomic write)
    temp_path = f"{file_path}.tmp"
    try:
        with open(temp_path, 'w') as f:
            f.write(content)

        # Move temporary file to final location
        os.replace(temp_path, file_path)

        return file_path
    except Exception as e:
        # Clean up temporary file if it exists
        if os.path.exists(temp_path):
            os.remove(temp_path)
        raise IOError(f"Failed to write DHCP config file: {str(e)}")


def generate_and_save_config(
    db: Session,
    user_id: Optional[int] = None,
    save_to_db: bool = True
) -> tuple[str, str]:
    """
    Generate DHCP configuration and save to both file and database

    Args:
        db: Database session
        user_id: ID of user generating the config
        save_to_db: Whether to save config to database

    Returns:
        Tuple of (config_content, file_path)

    Raises:
        IOError: If file cannot be written
    """
    # Generate configuration content
    config_content = generate_dhcpd_conf(db)

    # Save to file
    file_path = save_dhcp_config_to_file(config_content)

    # Save to database if requested
    if save_to_db:
        # Deactivate all previous configs
        db.query(DHCPConfig).update({DHCPConfig.is_active: False})

        # Get next version number
        last_config = db.query(DHCPConfig)\
            .order_by(DHCPConfig.version.desc())\
            .first()

        next_version = (last_config.version + 1) if last_config else 1

        # Create new config record
        dhcp_config = DHCPConfig(
            version=next_version,
            config_content=config_content,
            file_path=file_path,
            generated_by=user_id,
            is_active=True
        )

        db.add(dhcp_config)
        db.commit()
        db.refresh(dhcp_config)

    return config_content, file_path


def get_active_config(db: Session) -> Optional[DHCPConfig]:
    """
    Get the currently active DHCP configuration

    Args:
        db: Database session

    Returns:
        Active DHCP config or None
    """
    return db.query(DHCPConfig)\
        .filter(DHCPConfig.is_active == True)\
        .first()


def get_config_history(db: Session, limit: int = 10) -> list[DHCPConfig]:
    """
    Get DHCP configuration history

    Args:
        db: Database session
        limit: Maximum number of records to return

    Returns:
        List of DHCP configs, ordered by version descending
    """
    return db.query(DHCPConfig)\
        .order_by(DHCPConfig.version.desc())\
        .limit(limit)\
        .all()
